modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20GUI%20Effect%20Timer"
logoFile="icon.png"

[[mods]]
modId="guieffecttimer"
version="1.0"
displayName="GUI Effect Timer"
displayURL="https://serilum.com/mod/gui-effect-timer"
authors="Rick South"
description='''Displays time remaining text inside the mob effect badge on the screen.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, David Sanchez, drdog111, Michael W. S., t128, Tyler Behl, XAgent   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.guieffecttimer]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[7.92,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.guieffecttimer]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"